categorized_10 = {
    'acai': 'Healthy & Light',
    'afghani': 'Asian & Middle Eastern',
    'african': 'Global & Regional',
    'american': 'American & Fast Food',
    'arabic': 'Asian & Middle Eastern',
    'arabic sweets': 'Desserts & Bakery',
    'argentinian': 'Latin & South American',
    'asian': 'Asian & Middle Eastern',
    'bagel': 'Desserts & Bakery',
    'bakery': 'Desserts & Bakery',
    'bakery and cakes': 'Desserts & Bakery',
    'bbq': 'American & Fast Food',
    'beverages': 'Beverages',
    'biryani': 'Asian & Middle Eastern',
    'bowls': 'Healthy & Light',
    'brazilian': 'Latin & South American',
    'bread & bakery': 'Desserts & Bakery',
    'breakfast': 'Breakfast & Brunch',
    'british': 'European',
    'bubble tea': 'Beverages',
    'burgers': 'American & Fast Food',
    'burrito': 'Latin & South American',
    'cafe': 'Beverages',
    'cafeteria': 'Global & Regional',
    'cakes': 'Desserts & Bakery',
    'cakes and desserts': 'Desserts & Bakery',
    'calzone': 'European',
    'chicken': 'American & Fast Food',
    'chinese': 'Asian & Middle Eastern',
    'churros': 'Desserts & Bakery',
    'coffee': 'Beverages',
    'crepes': 'Desserts & Bakery',
    'curry': 'Asian & Middle Eastern',
    'desserts': 'Desserts & Bakery',
    'dim sum': 'Asian & Middle Eastern',
    'doner': 'Asian & Middle Eastern',
    'donuts': 'Desserts & Bakery',
    'dumplings': 'Asian & Middle Eastern',
    'egyptian': 'Asian & Middle Eastern',
    'emirati': 'Asian & Middle Eastern',
    'european': 'European',
    'falafel': 'Asian & Middle Eastern',
    'fast food': 'American & Fast Food',
    'filipino': 'Asian & Middle Eastern',
    'fish & chips': 'European',
    'french': 'European',
    'fried chicken': 'American & Fast Food',
    'frozen yogurt': 'Desserts & Bakery',
    'gelato': 'Desserts & Bakery',
    'georgian': 'European',
    'gluten free': 'Healthy & Light',
    'greek': 'European',
    'grills': 'American & Fast Food',
    'healthy': 'Healthy & Light',
    'hot dogs': 'American & Fast Food',
    'ice cream': 'Desserts & Bakery',
    'indian': 'Asian & Middle Eastern',
    'indonesian': 'Asian & Middle Eastern',
    'international': 'Global & Regional',
    'iranian': 'Asian & Middle Eastern',
    'iraqi': 'Asian & Middle Eastern',
    'italian': 'European',
    'jamaican': 'Global & Regional',
    'japanese': 'Asian & Middle Eastern',
    'jordanian': 'Asian & Middle Eastern',
    'juices': 'Beverages',
    'kebab': 'Asian & Middle Eastern',
    'keto': 'Healthy & Light',
    'korean': 'Asian & Middle Eastern',
    'koshary': 'Asian & Middle Eastern',
    'kuwaiti': 'Asian & Middle Eastern',
    'latin american': 'Latin & South American',
    'lebanese': 'Asian & Middle Eastern',
    'manaqeesh': 'Asian & Middle Eastern',
    'mandi': 'Asian & Middle Eastern',
    'mediterranean': 'European',
    'mexican': 'Latin & South American',
    'mezze': 'Asian & Middle Eastern',
    'middle eastern': 'Asian & Middle Eastern',
    'milkshakes': 'Beverages',
    'mongolian': 'Asian & Middle Eastern',
    'moroccan': 'Asian & Middle Eastern',
    'nepalese': 'Asian & Middle Eastern',
    'noodles': 'Asian & Middle Eastern',
    'north indian': 'Asian & Middle Eastern',
    'pakistani': 'Asian & Middle Eastern',
    'palestinian': 'Asian & Middle Eastern',
    'pancakes': 'Breakfast & Brunch',
    'pasta': 'European',
    'pastries': 'Desserts & Bakery',
    'pastries & sweets': 'Desserts & Bakery',
    'peruvian': 'Latin & South American',
    'pizza': 'European',
    'poke': 'Asian & Middle Eastern',
    'portuguese': 'European',
    'russian': 'European',
    'salad': 'Healthy & Light',
    'sandwiches': 'American & Fast Food',
    'saudi': 'Asian & Middle Eastern',
    'seafood': 'Global & Regional',
    'shawarma': 'Asian & Middle Eastern',
    'singaporean': 'Asian & Middle Eastern',
    'sliders': 'American & Fast Food',
    'smoothies': 'Beverages',
    'snacks': 'American & Fast Food',
    'soup': 'Global & Regional',
    'south indian': 'Asian & Middle Eastern',
    'spanish': 'European',
    'specialty_store': 'Global & Regional',
    'steaks': 'American & Fast Food',
    'street food': 'Global & Regional',
    'sushi': 'Asian & Middle Eastern',
    'syrian': 'Asian & Middle Eastern',
    'tacos': 'Latin & South American',
    'tea': 'Beverages',
    'thai': 'Asian & Middle Eastern',
    'tunisian': 'Asian & Middle Eastern',
    'turkish': 'Asian & Middle Eastern',
    'uzbek': 'Asian & Middle Eastern',
    'vegan': 'Healthy & Light',
    'vegetarian': 'Healthy & Light',
    'vietnamese': 'Asian & Middle Eastern',
    'waffles': 'Breakfast & Brunch',
    'wings': 'American & Fast Food',
    'wraps': 'American & Fast Food',
    'yemeni': 'Asian & Middle Eastern'
}

categorized_30 = {
    'acai': 'Healthy Bowls',
    'afghani': 'Central & South Asian',
    'african': 'African Cuisine',
    'american': 'American Cuisine',
    'arabic': 'Middle Eastern Cuisine',
    'arabic sweets': 'Middle Eastern Sweets',
    'argentinian': 'Latin & South American',
    'asian': 'Asian Fusion',
    'bagel': 'Breads & Bakery',
    'bakery': 'Breads & Bakery',
    'bakery and cakes': 'Breads & Bakery',
    'bbq': 'American Grill & BBQ',
    'beverages': 'Beverages',
    'biryani': 'Central & South Asian',
    'bowls': 'Healthy Bowls',
    'brazilian': 'Latin & South American',
    'bread & bakery': 'Breads & Bakery',
    'breakfast': 'Breakfast & Brunch',
    'british': 'European Cuisine',
    'bubble tea': 'Sweet Beverages',
    'burgers': 'Burgers & Sandwiches',
    'burrito': 'Mexican Cuisine',
    'cafe': 'Café & Coffee',
    'cafeteria': 'Café & Coffee',
    'cakes': 'Sweets & Desserts',
    'cakes and desserts': 'Sweets & Desserts',
    'calzone': 'Italian Cuisine',
    'chicken': 'Chicken Dishes',
    'chinese': 'East Asian Cuisine',
    'churros': 'Sweets & Desserts',
    'coffee': 'Café & Coffee',
    'crepes': 'Sweets & Desserts',
    'curry': 'Central & South Asian',
    'desserts': 'Sweets & Desserts',
    'dim sum': 'East Asian Cuisine',
    'doner': 'Middle Eastern Cuisine',
    'donuts': 'Sweets & Desserts',
    'dumplings': 'East Asian Cuisine',
    'egyptian': 'Middle Eastern Cuisine',
    'emirati': 'Middle Eastern Cuisine',
    'european': 'European Cuisine',
    'falafel': 'Middle Eastern Cuisine',
    'fast food': 'Fast Food',
    'filipino': 'Southeast Asian',
    'fish & chips': 'European Cuisine',
    'french': 'European Cuisine',
    'fried chicken': 'Chicken Dishes',
    'frozen yogurt': 'Frozen Desserts',
    'gelato': 'Frozen Desserts',
    'georgian': 'European Cuisine',
    'gluten free': 'Healthy & Dietary',
    'greek': 'European Cuisine',
    'grills': 'American Grill & BBQ',
    'healthy': 'Healthy & Dietary',
    'hot dogs': 'Fast Food',
    'ice cream': 'Frozen Desserts',
    'indian': 'Central & South Asian',
    'indonesian': 'Southeast Asian',
    'international': 'Global Fusion',
    'iranian': 'Middle Eastern Cuisine',
    'iraqi': 'Middle Eastern Cuisine',
    'italian': 'Italian Cuisine',
    'jamaican': 'Caribbean & Island',
    'japanese': 'East Asian Cuisine',
    'jordanian': 'Middle Eastern Cuisine',
    'juices': 'Beverages',
    'kebab': 'Middle Eastern Cuisine',
    'keto': 'Healthy & Dietary',
    'korean': 'East Asian Cuisine',
    'koshary': 'Middle Eastern Cuisine',
    'kuwaiti': 'Middle Eastern Cuisine',
    'latin american': 'Latin & South American',
    'lebanese': 'Middle Eastern Cuisine',
    'manaqeesh': 'Middle Eastern Cuisine',
    'mandi': 'Middle Eastern Cuisine',
    'mediterranean': 'Mediterranean Cuisine',
    'mexican': 'Mexican Cuisine',
    'mezze': 'Middle Eastern Cuisine',
    'middle eastern': 'Middle Eastern Cuisine',
    'milkshakes': 'Sweet Beverages',
    'mongolian': 'East Asian Cuisine',
    'moroccan': 'Middle Eastern Cuisine',
    'nepalese': 'Central & South Asian',
    'noodles': 'East Asian Cuisine',
    'north indian': 'Central & South Asian',
    'pakistani': 'Central & South Asian',
    'palestinian': 'Middle Eastern Cuisine',
    'pancakes': 'Breakfast & Brunch',
    'pasta': 'Italian Cuisine',
    'pastries': 'Breads & Bakery',
    'pastries & sweets': 'Sweets & Desserts',
    'peruvian': 'Latin & South American',
    'pizza': 'Italian Cuisine',
    'poke': 'Southeast Asian',
    'portuguese': 'European Cuisine',
    'russian': 'European Cuisine',
    'salad': 'Healthy Bowls',
    'sandwiches': 'Burgers & Sandwiches',
    'saudi': 'Middle Eastern Cuisine',
    'seafood': 'Seafood',
    'shawarma': 'Middle Eastern Cuisine',
    'singaporean': 'Southeast Asian',
    'sliders': 'Fast Food',
    'smoothies': 'Sweet Beverages',
    'snacks': 'Fast Food',
    'soup': 'Soups & Stews',
    'south indian': 'Central & South Asian',
    'spanish': 'European Cuisine',
    'specialty_store': 'Global Fusion',
    'steaks': 'American Grill & BBQ',
    'street food': 'Street Food',
    'sushi': 'East Asian Cuisine',
    'syrian': 'Middle Eastern Cuisine',
    'tacos': 'Mexican Cuisine',
    'tea': 'Beverages',
    'thai': 'Southeast Asian',
    'tunisian': 'Middle Eastern Cuisine',
    'turkish': 'Middle Eastern Cuisine',
    'uzbek': 'Central & South Asian',
    'vegan': 'Healthy & Dietary',
    'vegetarian': 'Healthy & Dietary',
    'vietnamese': 'Southeast Asian',
    'waffles': 'Breakfast & Brunch',
    'wings': 'Chicken Dishes',
    'wraps': 'Wraps & Rolls',
    'yemeni': 'Middle Eastern Cuisine'
}

categorized_50 = {
    'acai': 'Healthy Bowls',
    'afghani': 'Central Asian',
    'african': 'African Cuisine',
    'american': 'American Fast Food',
    'arabic': 'Middle Eastern',
    'arabic sweets': 'Bakery & Sweets',
    'argentinian': 'Latin American',
    'asian': 'Asian Fusion',
    'bagel': 'Bakery Items',
    'bakery': 'Bakery Items',
    'bakery and cakes': 'Bakery & Cakes',
    'bbq': 'Grilled & BBQ',
    'beverages': 'Beverages',
    'biryani': 'South Asian Rice Dishes',
    'bowls': 'Healthy Bowls',
    'brazilian': 'Latin American',
    'bread & bakery': 'Bakery Items',
    'breakfast': 'Breakfast Dishes',
    'british': 'European',
    'bubble tea': 'Specialty Drinks',
    'burgers': 'American Fast Food',
    'burrito': 'Mexican Cuisine',
    'cafe': 'Cafés & Coffee',
    'cafeteria': 'Casual Dining',
    'cakes': 'Desserts & Cakes',
    'cakes and desserts': 'Desserts & Cakes',
    'calzone': 'Italian Cuisine',
    'chicken': 'Chicken Dishes',
    'chinese': 'Chinese Cuisine',
    'churros': 'Bakery & Sweets',
    'coffee': 'Cafés & Coffee',
    'crepes': 'Bakery & Sweets',
    'curry': 'South Asian Curries',
    'desserts': 'Desserts & Cakes',
    'dim sum': 'Chinese Cuisine',
    'doner': 'Turkish Cuisine',
    'donuts': 'Bakery & Sweets',
    'dumplings': 'East Asian Dumplings',
    'egyptian': 'Middle Eastern',
    'emirati': 'Gulf Cuisine',
    'european': 'European',
    'falafel': 'Middle Eastern Snacks',
    'fast food': 'American Fast Food',
    'filipino': 'Southeast Asian',
    'fish & chips': 'British Cuisine',
    'french': 'European',
    'fried chicken': 'American Fast Food',
    'frozen yogurt': 'Frozen Desserts',
    'gelato': 'Frozen Desserts',
    'georgian': 'Eastern European',
    'gluten free': 'Healthy Options',
    'greek': 'Mediterranean',
    'grills': 'Grilled & BBQ',
    'healthy': 'Healthy Options',
    'hot dogs': 'American Fast Food',
    'ice cream': 'Frozen Desserts',
    'indian': 'Indian Cuisine',
    'indonesian': 'Southeast Asian',
    'international': 'Global Fusion',
    'iranian': 'Middle Eastern',
    'iraqi': 'Middle Eastern',
    'italian': 'Italian Cuisine',
    'jamaican': 'Caribbean Cuisine',
    'japanese': 'Japanese Cuisine',
    'jordanian': 'Middle Eastern',
    'juices': 'Fresh Juices',
    'kebab': 'Middle Eastern Grilled',
    'keto': 'Healthy Options',
    'korean': 'Korean Cuisine',
    'koshary': 'Middle Eastern',
    'kuwaiti': 'Gulf Cuisine',
    'latin american': 'Latin American',
    'lebanese': 'Middle Eastern',
    'manaqeesh': 'Levantine Baked',
    'mandi': 'Gulf Cuisine',
    'mediterranean': 'Mediterranean',
    'mexican': 'Mexican Cuisine',
    'mezze': 'Middle Eastern Mezze',
    'middle eastern': 'Middle Eastern',
    'milkshakes': 'Specialty Drinks',
    'mongolian': 'East Asian',
    'moroccan': 'North African',
    'nepalese': 'South Asian',
    'noodles': 'Asian Noodles',
    'north indian': 'Indian Cuisine',
    'pakistani': 'South Asian',
    'palestinian': 'Middle Eastern',
    'pancakes': 'Breakfast Dishes',
    'pasta': 'Italian Cuisine',
    'pastries': 'Bakery & Sweets',
    'pastries & sweets': 'Bakery & Sweets',
    'peruvian': 'Latin American',
    'pizza': 'Italian Cuisine',
    'poke': 'Hawaiian Cuisine',
    'portuguese': 'European',
    'russian': 'Eastern European',
    'salad': 'Healthy Bowls',
    'sandwiches': 'American Fast Food',
    'saudi': 'Gulf Cuisine',
    'seafood': 'Seafood Cuisine',
    'shawarma': 'Middle Eastern Grilled',
    'singaporean': 'Southeast Asian',
    'sliders': 'American Fast Food',
    'smoothies': 'Fresh Juices',
    'snacks': 'Street Food',
    'soup': 'Soups & Stews',
    'south indian': 'Indian Cuisine',
    'spanish': 'European',
    'specialty_store': 'Specialty & Gourmet',
    'steaks': 'Grilled & BBQ',
    'street food': 'Street Food',
    'sushi': 'Japanese Cuisine',
    'syrian': 'Middle Eastern',
    'tacos': 'Mexican Cuisine',
    'tea': 'Beverages',
    'thai': 'Southeast Asian',
    'tunisian': 'North African',
    'turkish': 'Turkish Cuisine',
    'uzbek': 'Central Asian',
    'vegan': 'Healthy Options',
    'vegetarian': 'Healthy Options',
    'vietnamese': 'Southeast Asian',
    'waffles': 'Breakfast Dishes',
    'wings': 'Chicken Dishes',
    'wraps': 'Wraps & Rolls',
    'yemeni': 'Gulf Cuisine'
}

categorized_70 = {
    'indian': 'South Asian Curries',
    'north indian': 'South Asian Curries',
    'south indian': 'South Indian Specialties',
    'biryani': 'South Asian Rice Dishes',
    'curry': 'South Asian Curries',
    'shawarma': 'Arabian Grilled Meats',
    'kebab': 'Arabian Grilled Meats',
    'grills': 'Grill & Barbecue',
    'mandi': 'Yemeni & Gulf Rice Dishes',
    'doner': 'Turkish Street Food',
    'arabic sweets': 'Middle Eastern Sweets',
    'pastries': 'Bakeries & Pastries',
    'pastries & sweets': 'Bakeries & Pastries',
    'lebanese': 'Levantine Cuisine',
    'palestinian': 'Levantine Cuisine',
    'syrian': 'Levantine Cuisine',
    'jordanian': 'Levantine Cuisine',
    'emirati': 'Gulf Cuisine',
    'saudi': 'Gulf Cuisine',
    'kuwaiti': 'Gulf Cuisine',
    'moroccan': 'North African Cuisine',
    'tunisian': 'North African Cuisine',
    'chinese': 'Chinese Cuisine',
    'japanese': 'Japanese Cuisine',
    'korean': 'Korean Cuisine',
    'sushi': 'Japanese Sushi',
    'dim sum': 'Chinese Dim Sum',
    'noodles': 'Asian Noodle Dishes',
    'dumplings': 'Asian Dumplings',
    'thai': 'Thai Cuisine',
    'vietnamese': 'Vietnamese Cuisine',
    'indonesian': 'Indonesian Cuisine',
    'filipino': 'Filipino Cuisine',
    'singaporean': 'Singaporean Cuisine',
    'pakistani': 'South Asian Curries',
    'afghani': 'Central Asian Cuisine',
    'nepalese': 'Nepalese Cuisine',
    'french': 'Western European Cuisine',
    'spanish': 'Western European Cuisine',
    'portuguese': 'Western European Cuisine',
    'italian': 'Italian Cuisine',
    'greek': 'Mediterranean Cuisine',
    'russian': 'Eastern European Cuisine',
    'georgian': 'Caucasus Cuisine',
    'mediterranean': 'Mediterranean Cuisine',
    'mezze': 'Middle Eastern Mezze',
    'manaqeesh': 'Middle Eastern Bakery',
    'falafel': 'Middle Eastern Mezze',
    'mexican': 'Mexican Cuisine',
    'latin american': 'Latin American Cuisine',
    'peruvian': 'Peruvian Cuisine',
    'argentinian': 'South American Grill',
    'brazilian': 'South American Grill',
    'american': 'American Cuisine',
    'burgers': 'American Fast Food',
    'fried chicken': 'American Fast Food',
    'hot dogs': 'American Fast Food',
    'sliders': 'American Fast Food',
    'bbq': 'Grill & Barbecue',
    'steaks': 'Grill & Barbecue',
    'breakfast': 'Breakfast & Brunch',
    'pancakes': 'Breakfast & Brunch',
    'waffles': 'Breakfast & Brunch',
    'donuts': 'Bakeries & Pastries',
    'churros': 'Bakeries & Pastries',
    'crepes': 'Bakeries & Pastries',
    'cakes': 'Desserts & Cakes',
    'cakes and desserts': 'Desserts & Cakes',
    'bakery': 'Bakeries & Pastries',
    'bakery and cakes': 'Bakeries & Pastries',
    'bread & bakery': 'Bakeries & Pastries',
    'ice cream': 'Cold Desserts',
    'gelato': 'Cold Desserts',
    'frozen yogurt': 'Cold Desserts',
    'coffee': 'Cafés & Coffee',
    'cafe': 'Cafés & Coffee',
    'cafeteria': 'Cafés & Coffee',
    'tea': 'Cafés & Tea',
    'healthy': 'Healthy Choices',
    'keto': 'Healthy Choices',
    'gluten free': 'Healthy Choices',
    'vegan': 'Healthy Choices',
    'vegetarian': 'Healthy Choices',
    'salad': 'Healthy Bowls & Greens',
    'acai': 'Healthy Bowls & Greens',
    'bowls': 'Healthy Bowls & Greens',
    'fast food': 'Fast Food',
    'street food': 'Street Food',
    'snacks': 'Street Food',
    'sandwiches': 'Sandwiches & Wraps',
    'wraps': 'Sandwiches & Wraps',
    'bagel': 'Sandwiches & Wraps',
    'pizza': 'Pizza & Pasta',
    'pasta': 'Pizza & Pasta',
    'calzone': 'Pizza & Pasta',
    'soup': 'Soups & Comfort',
    'seafood': 'Seafood Dishes',
    'fish & chips': 'Seafood Dishes',
    'juices': 'Smoothies & Juices',
    'bubble tea': 'Specialty Drinks',
    'smoothies': 'Smoothies & Juices',
    'milkshakes': 'Specialty Drinks',
    'beverages': 'Beverages',
    'specialty_store': 'Specialty Shops',
    'international': 'International Fusion',
    'asian': 'Asian Fusion',
    'european': 'European Cuisine',
    'british': 'British Cuisine',
    'iranian': 'Persian Cuisine',
    'iraqi': 'Iraqi Cuisine',
    'african': 'African Cuisine',
    'koshary': 'Egyptian Street Food',
    'poke': 'Hawaiian Cuisine',
    'arabic': 'Middle Eastern Cuisine',
    'burrito': 'Mexican Cuisine',
    'chicken': 'Chicken Dishes',
    'desserts': 'Desserts & Cakes',
    'egyptian': 'Egyptian Cuisine',
    'jamaican': 'Caribbean Cuisine',
    'middle eastern': 'Middle Eastern Cuisine',
    'mongolian': 'Mongolian Cuisine',
    'tacos': 'Mexican Cuisine',
    'turkish': 'Turkish Cuisine',
    'uzbek': 'Central Asian Cuisine',
    'wings': 'Chicken Dishes',
    'yemeni': 'Yemeni & Gulf Rice Dishes'
}

categorized_90 = {
    'acai': 'Acai Bowls',
    'afghani': 'Central Asian Cuisine',
    'african': 'African Cuisine',
    'american': 'American Classics',
    'arabic': 'Middle Eastern Cuisine',
    'arabic sweets': 'Middle Eastern Sweets',
    'argentinian': 'South American Grill',
    'asian': 'Asian Fusion',
    'bagel': 'Sandwiches & Wraps',
    'bakery': 'Bakery',
    'bakery and cakes': 'Bakery',
    'bbq': 'Grill & Barbecue',
    'beverages': 'General Beverages',
    'biryani': 'South Asian Rice Dishes',
    'bowls': 'Nutrient Bowls',
    'brazilian': 'South American Grill',
    'bread & bakery': 'Bread & Pastry Bakery',
    'breakfast': 'Breakfast & Brunch',
    'british': 'British Cuisine',
    'bubble tea': 'Specialty Drinks',
    'burgers': 'American Burgers',
    'burrito': 'Mexican',
    'cafe': 'Cafés',
    'cafeteria': 'Cafés',
    'cakes': 'Bakery',
    'cakes and desserts': 'Bakery',
    'calzone': 'Italian Calzone',
    'chicken': 'General Chicken Dishes',
    'chinese': 'Chinese Cuisine',
    'churros': 'Spanish Churros',
    'coffee': 'Cafés',
    'crepes': 'French Crepes',
    'curry': 'South Asian Curries',
    'desserts': 'Desserts & Cakes',
    'dim sum': 'Chinese Dim Sum',
    'doner': 'Turkish Doner',
    'donuts': 'Bakery',
    'dumplings': 'Asian Dumplings',
    'egyptian': 'Egyptian Cuisine',
    'emirati': 'Gulf Cuisine',
    'european': 'European Cuisine',
    'falafel': 'Levantine Falafel',
    'fast food': 'Generic Fast Food',
    'filipino': 'Filipino Cuisine',
    'fish & chips': 'Seafood Dishes',
    'french': 'Western European Cuisine',
    'fried chicken': 'American Fried Chicken',
    'frozen yogurt': 'Cold Desserts',
    'gelato': 'Cold Desserts',
    'georgian': 'Caucasus Cuisine',
    'gluten free': 'Gluten-Free Options',
    'greek': 'Mediterranean Cuisine',
    'grills': 'International Grills',
    'healthy': 'Health-Conscious',
    'hot dogs': 'American Street Food',
    'ice cream': 'Cold Desserts',
    'indian': 'South Asian Curries',
    'indonesian': 'Indonesian Cuisine',
    'international': 'International Fusion',
    'iranian': 'Persian Cuisine',
    'iraqi': 'Iraqi Cuisine',
    'italian': 'Italian Cuisine',
    'jamaican': 'Caribbean Cuisine',
    'japanese': 'Japanese Cuisine',
    'jordanian': 'Levantine Cuisine',
    'juices': 'Juice Bars',
    'kebab': 'Middle Eastern Kebabs',
    'keto': 'Keto-Specific',
    'korean': 'Korean Cuisine',
    'koshary': 'Egyptian Koshary',
    'kuwaiti': 'Gulf Cuisine',
    'latin american': 'Latin American Cuisine',
    'lebanese': 'Levantine Cuisine',
    'manaqeesh': 'Arabic Flatbreads',
    'mandi': 'Yemeni & Gulf Rice Dishes',
    'mediterranean': 'Mediterranean Cuisine',
    'mexican': 'Mexican',
    'mezze': 'Arabic Mezze',
    'middle eastern': 'Middle Eastern Cuisine',
    'milkshakes': 'Milkshake Bars',
    'mongolian': 'Mongolian Cuisine',
    'moroccan': 'North African Cuisine',
    'nepalese': 'Nepalese Cuisine',
    'noodles': 'Asian Noodles',
    'north indian': 'South Asian Curries',
    'pakistani': 'South Asian Curries',
    'palestinian': 'Levantine Cuisine',
    'pancakes': 'Breakfast & Brunch',
    'pasta': 'Italian Pasta',
    'pastries': 'Bakery',
    'pastries & sweets': 'Bakeries & Pastries',
    'peruvian': 'Peruvian Cuisine',
    'pizza': 'Italian Pizza',
    'poke': 'Hawaiian Poke',
    'portuguese': 'Western European Cuisine',
    'russian': 'Eastern European Cuisine',
    'salad': 'Salad Bars',
    'sandwiches': 'Sandwiches & Wraps',
    'saudi': 'Gulf Cuisine',
    'seafood': 'Seafood Dishes',
    'shawarma': 'Levantine Shawarma',
    'singaporean': 'Singaporean Cuisine',
    'sliders': 'American Street Food',
    'smoothies': 'Smoothie Bars',
    'snacks': 'Casual Snacks',
    'soup': 'Soups & Comfort',
    'south indian': 'South Indian Specialties',
    'spanish': 'Western European Cuisine',
    'specialty_store': 'Specialty Shops',
    'steaks': 'Grill & Barbecue',
    'street food': 'Global Street Food',
    'sushi': 'Japanese Sushi',
    'syrian': 'Levantine Cuisine',
    'tacos': 'Mexican',
    'tea': 'Cafés',
    'thai': 'Thai Cuisine',
    'tunisian': 'North African Cuisine',
    'turkish': 'Turkish Cuisine',
    'uzbek': 'Central Asian Cuisine',
    'vegan': 'Vegan Cuisine',
    'vegetarian': 'Vegetarian Cuisine',
    'vietnamese': 'Vietnamese Cuisine',
    'waffles': 'Breakfast & Brunch',
    'wings': 'Fried Wings',
    'wraps': 'Sandwiches & Wraps',
    'yemeni': 'Yemeni & Gulf Rice Dishes'
}

